services:
  frontend:
    build:
      context: ./frontend  # Path to the frontend Dockerfile
    command: npm run test #run node test
    depends_on:
      - backend  # Ensure the backend starts before the frontend

  backend:
    build:
      context: ./backend  # Path to the backend Dockerfile
    command: mvn test  # run maven test
    environment:
      CORS_ALLOWED_ORIGINS: "http://localhost:3001"  # Replace with your allowed origins
      CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE"
      CORS_ALLOWED_HEADERS: "Content-Type,Authorization"
      JWT_SECRET_KEY: "jxgEQeXHuRq3VBbaYFLkAFkazF1C4Un4"
    volumes:
      - sqlite_data_task_management_tool:/data

volumes:
  sqlite_data_task_management_tool: