services:
  frontend:
    build:
      context: ./frontend  # Path to the frontend Dockerfile
      dockerfile: Dockerfile  # Dockerfile name
    ports:
      - "3001:80"  # Map host port 3000 to container port 80
    depends_on:
      - backend  # Ensure the backend starts before the frontend

  backend:
    build:
      context: ./backend  # Path to the backend Dockerfile
      dockerfile: Dockerfile  # Dockerfile name
    ports:
      - "8083:8080"  # Map host port 8080 to container port 8080

networks:
  default:
    driver: bridge  # Use the default bridge network